In [1]:
import numpy as np


In [2]:
np.arange(1,5,3)

array([1, 4])

In [3]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [4]:
test = np.ones((10,2))

In [5]:
test

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
np.random.rand(5)

array([0.58773327, 0.89500143, 0.6964204 , 0.13373937, 0.17412543])

In [9]:
np.random.rand(5,5)


array([[0.76903607, 0.06848739, 0.42162534, 0.95014523, 0.54777712],
       [0.29364462, 0.79928872, 0.40974887, 0.23555947, 0.7816604 ],
       [0.51262729, 0.47577988, 0.35621727, 0.964661  , 0.72398511],
       [0.37557125, 0.44529935, 0.34860422, 0.10692504, 0.09106167],
       [0.31122431, 0.67599766, 0.5176935 , 0.04717125, 0.05425765]])

In [10]:
np.random.randn(2,4)

array([[-0.28744564, -2.47305942, -0.32202233, -0.71696704],
       [ 0.86625058, -1.12968417,  0.07456307,  0.19137326]])

In [11]:
np.random.randint(1,5,10)

array([4, 4, 1, 2, 1, 2, 1, 1, 2, 4])

In [12]:
arr = np.arange(25)

In [13]:
ranarr = np.random.randint(0,50,10)

In [14]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
ranarr.max()

38

In [16]:
ranarr.min()

2

In [17]:
ranarr.argmax()

9

In [18]:
ranarr.argmin()

5

In [19]:
ranarr.shape

(10,)

In [42]:
ranarr.dtype

dtype('int32')

In [43]:
from numpy.random import randint as npint


In [45]:
npint(1)

0